import {ConstantData} from '../types/dataItem'

export const data: ConstantData[] = [
  {
    "id": 29,
    "week": 1,
    "employmentPlan": 0,
    "dismissalPlan": 0,
    "employmentFact": 0,
    "dismissalFact": 0,
    "sick": 0,
    "vocation": 0,
    "toProject": 0,
    "fromProject": 5,
  },
  {
    "id": 30,
    "week": 2,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 7,
    "dismissalFact": 1,
    "sick": 0,
    "vocation": 3,
    "toProject": 8,
    "fromProject": 6,
  },
  {
    "id": 31,
    "week": 3,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 1,
    "dismissalFact": 1,
    "sick": 1,
    "vocation": 3,
    "toProject": 5,
    "fromProject": 3,
  },
  {
    "id": 32,
    "week": 4,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 0,
    "dismissalFact": 1,
    "sick": 2,
    "vocation": 3,
    "toProject": 4,
    "fromProject": 2,
  },
  {
    "id": 33,
    "week": 5,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 2,
    "sick": 1,
    "vocation": 3,
    "toProject": 4,
    "fromProject": 4,
  },
  {
    "id": 34,
    "week": 6,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 0,
    "dismissalFact": 1,
    "sick": 1,
    "vocation": 3,
    "toProject": 5,
    "fromProject": 0,
  },
  {
    "id": 35,
    "week": 7,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 4,
    "dismissalFact": 2,
    "sick": 3,
    "vocation": 4,
    "toProject": 7,
    "fromProject": 6,
  },
  {
    "id": 36,
    "week": 8,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 2,
    "sick": 0,
    "vocation": 1,
    "toProject": 3,
    "fromProject": 3,
  },
  {
    "id": 37,
    "week": 9,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 3,
    "dismissalFact": 0,
    "sick": 1,
    "vocation": 3,
    "toProject": 10,
    "fromProject": 3,
  },
  {
    "id": 38,
    "week": 10,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 1,
    "dismissalFact": 2,
    "sick": 2,
    "vocation": 4,
    "toProject": 4,
    "fromProject": 2,
  },
  {
    "id": 39,
    "week": 11,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 1,
    "dismissalFact": 1,
    "sick": 2,
    "vocation": 5,
    "toProject": 4,
    "fromProject": 4,
  },
  {
    "id": 40,
    "week": 12,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 6,
    "dismissalFact": 1,
    "sick": 1,
    "vocation": 4,
    "toProject": 10,
    "fromProject": 2,
  },
  {
    "id": 41,
    "week": 13,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 1,
    "dismissalFact": 0,
    "sick": 0,
    "vocation": 2,
    "toProject": 8,
    "fromProject": 4,
  },
  {
    "id": 42,
    "week": 14,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 5,
    "dismissalFact": 0,
    "sick": 1,
    "vocation": 5,
    "toProject": 2,
    "fromProject": 3,
  },
  {
    "id": 43,
    "week": 15,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 0,
    "dismissalFact": 3,
    "sick": 1,
    "vocation": 6,
    "toProject": 5,
    "fromProject": 3,
  },
  {
    "id": 44,
    "week": 16,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 0,
    "sick": 1,
    "vocation": 9,
    "toProject": 2,
    "fromProject": 4,
  },
  {
    "id": 45,
    "week": 17,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 1,
    "sick": 1,
    "vocation": 5,
    "toProject": 3,
    "fromProject": 3,
  },
  {
    "id": 46,
    "week": 18,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 0,
    "dismissalFact": 4,
    "sick": 2,
    "vocation": 3,
    "toProject": 3,
    "fromProject": 4,
  },
  {
    "id": 47,
    "week": 19,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 3,
    "dismissalFact": 1,
    "sick": 1,
    "vocation": 2,
    "toProject": 7,
    "fromProject": 3,
  },
  {
    "id": 48,
    "week": 20,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 1,
    "dismissalFact": 0,
    "sick": 1,
    "vocation": 2,
    "toProject": 9,
    "fromProject": 4,
  },
  {
    "id": 49,
    "week": 21,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 1,
    "dismissalFact": 1,
    "sick": 2,
    "vocation": 4,
    "toProject": 10,
    "fromProject": 3,
  },
  {
    "id": 50,
    "week": 22,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 3,
    "dismissalFact": 0,
    "sick": 4,
    "vocation": 6,
    "toProject": 5,
    "fromProject": 3,
  },
  {
    "id": 51,
    "week": 23,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 0,
    "sick": 3,
    "vocation": 6,
    "toProject": 9,
    "fromProject": 5,
  },
  {
    "id": 52,
    "week": 24,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 1,
    "sick": 2,
    "vocation": 7,
    "toProject": 1,
    "fromProject": 3,
  },
  {
    "id": 53,
    "week": 25,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 7,
    "dismissalFact": 0,
    "sick": 2,
    "vocation": 8,
    "toProject": 4,
    "fromProject": 2,
  },
  {
    "id": 54,
    "week": 26,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 6,
    "dismissalFact": 1,
    "sick": 2,
    "vocation": 9,
    "toProject": 4,
    "fromProject": 2,
  },
  {
    "id": 55,
    "week": 27,
    "employmentPlan": 4,
    "dismissalPlan": 1,
    "employmentFact": 1,
    "dismissalFact": 2,
    "sick": 2,
    "vocation": 12,
    "toProject": 3,
    "fromProject": 2,
  },
  {
    "id": 56,
    "week": 28,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 3,
    "dismissalFact": 0,
    "sick": 1,
    "vocation": 5,
    "toProject": 13,
    "fromProject": 2,
  },
  {
    "id": 57,
    "week": 29,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 5,
    "dismissalFact": 4,
    "sick": 2,
    "vocation": 2,
    "toProject": 9,
    "fromProject": 2,
  },
  {
    "id": 58,
    "week": 30,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 2,
    "sick": 3,
    "vocation": 4,
    "toProject": 2,
    "fromProject": 3,
  },
  {
    "id": 59,
    "week": 31,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 5,
    "dismissalFact": 2,
    "sick": 2,
    "vocation": 1,
    "toProject": 4,
    "fromProject": 4,
  },
  {
    "id": 60,
    "week": 32,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 2,
    "sick": 2,
    "vocation": 0,
    "toProject": 6,
    "fromProject": 3,
  },
  {
    "id": 61,
    "week": 33,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 1,
    "dismissalFact": 1,
    "sick": 4,
    "vocation": 2,
    "toProject": 4,
    "fromProject": 2,
  },
  {
    "id": 62,
    "week": 34,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 0,
    "sick": 0,
    "vocation": 2,
    "toProject": 2,
    "fromProject": 0,
  },
  {
    "id": 63,
    "week": 35,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 1,
    "dismissalFact": 2,
    "sick": 2,
    "vocation": 1,
    "toProject": 4,
    "fromProject": 2,
  },
  {
    "id": 64,
    "week": 36,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 1,
    "dismissalFact": 1,
    "sick": 1,
    "vocation": 4,
    "toProject": 2,
    "fromProject": 2,
  },
  {
    "id": 65,
    "week": 37,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 5,
    "dismissalFact": 1,
    "sick": 1,
    "vocation": 2,
    "toProject": 2,
    "fromProject": 2,
  },
  {
    "id": 66,
    "week": 38,
    "employmentPlan": 4,
    "dismissalPlan": 1,
    "employmentFact": 3,
    "dismissalFact": 1,
    "sick": 1,
    "vocation": 2,
    "toProject": 2,
    "fromProject": 2,
  },
  {
    "id": 67,
    "week": 39,
    "employmentPlan": 4,
    "dismissalPlan": 1,
    "employmentFact": 3,
    "dismissalFact": 1,
    "sick": 1,
    "vocation": 2,
    "toProject": 2,
    "fromProject": 2,
  },
  {
    "id": 68,
    "week": 40,
    "employmentPlan": 4,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 1,
    "sick": 2,
    "vocation": 2,
    "toProject": 4,
    "fromProject": 2,
  },
  {
    "id": 69,
    "week": 41,
    "employmentPlan": 4,
    "dismissalPlan": 1,
    "employmentFact": 3,
    "dismissalFact": 1,
    "sick": 2,
    "vocation": 2,
    "toProject": 3,
    "fromProject": 2,
  },
]
