import {ConstantData} from '../types/dataItem'

export const data: ConstantData[] = [
  {
    "id": 1,
    "week": 1,
    "employmentPlan": 0,
    "dismissalPlan": 0,
    "employmentFact": 0,
    "dismissalFact": 0,
    "sick": 0,
    "vocation": 0,
    "toProject": 0,
    "fromProject": 0
  },
  {
    "id": 2,
    "week": 2,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 7,
    "sick": 1,
    "vocation": 0,
    "toProject": 3,
    "fromProject": 8
  },
  {
    "id": 3,
    "week": 3,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 1,
    "sick": 1,
    "vocation": 1,
    "toProject": 3,
    "fromProject": 5
  },
  {
    "id": 4,
    "week": 4,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 0,
    "sick": 1,
    "vocation": 2,
    "toProject": 3,
    "fromProject": 4
  },
  {
    "id": 5,
    "week": 5,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 2,
    "sick": 2,
    "vocation": 1,
    "toProject": 3,
    "fromProject": 4
  },
  {
    "id": 6,
    "week": 6,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 0,
    "sick": 1,
    "vocation": 1,
    "toProject": 3,
    "fromProject": 5
  },
  {
    "id": 7,
    "week": 7,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 4,
    "sick": 2,
    "vocation": 3,
    "toProject": 4,
    "fromProject": 7
  },
  {
    "id": 8,
    "week": 8,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 2,
    "sick": 2,
    "vocation": 0,
    "toProject": 1,
    "fromProject": 3
  },
  {
    "id": 9,
    "week": 9,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 3,
    "sick": 0,
    "vocation": 1,
    "toProject": 3,
    "fromProject": 10
  },
  {
    "id": 10,
    "week": 10,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 1,
    "sick": 2,
    "vocation": 2,
    "toProject": 4,
    "fromProject": 4
  },
  {
    "id": 11,
    "week": 11,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 1,
    "sick": 1,
    "vocation": 2,
    "toProject": 5,
    "fromProject": 4
  },
  {
    "id": 12,
    "week": 12,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 6,
    "sick": 1,
    "vocation": 1,
    "toProject": 4,
    "fromProject": 10
  },
  {
    "id": 13,
    "week": 13,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 1,
    "sick": 0,
    "vocation": 0,
    "toProject": 2,
    "fromProject": 8
  },
  {
    "id": 14,
    "week": 14,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 5,
    "sick": 0,
    "vocation": 1,
    "toProject": 5,
    "fromProject": 2
  },
  {
    "id": 15,
    "week": 15,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 0,
    "sick": 3,
    "vocation": 1,
    "toProject": 6,
    "fromProject": 5
  },
  {
    "id": 16,
    "week": 16,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 2,
    "sick": 0,
    "vocation": 1,
    "toProject": 9,
    "fromProject": 2
  },
  {
    "id": 17,
    "week": 17,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 2,
    "sick": 1,
    "vocation": 1,
    "toProject": 5,
    "fromProject": 3
  },
  {
    "id": 18,
    "week": 18,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 0,
    "sick": 4,
    "vocation": 2,
    "toProject": 3,
    "fromProject": 3
  },
  {
    "id": 19,
    "week": 19,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 3,
    "sick": 1,
    "vocation": 1,
    "toProject": 2,
    "fromProject": 7
  },
  {
    "id": 20,
    "week": 20,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 1,
    "sick": 0,
    "vocation": 1,
    "toProject": 2,
    "fromProject": 9
  },
  {
    "id": 21,
    "week": 21,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 1,
    "sick": 1,
    "vocation": 2,
    "toProject": 4,
    "fromProject": 10
  },
  {
    "id": 22,
    "week": 22,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 3,
    "sick": 0,
    "vocation": 4,
    "toProject": 6,
    "fromProject": 5
  },
  {
    "id": 23,
    "week": 23,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 2,
    "sick": 0,
    "vocation": 3,
    "toProject": 6,
    "fromProject": 9
  },
  {
    "id": 24,
    "week": 24,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 2,
    "sick": 1,
    "vocation": 2,
    "toProject": 7,
    "fromProject": 1
  },
  {
    "id": 25,
    "week": 25,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 7,
    "sick": 0,
    "vocation": 2,
    "toProject": 8,
    "fromProject": 4
  },
  {
    "id": 26,
    "week": 26,
    "employmentPlan": 3,
    "dismissalPlan": 1,
    "employmentFact": 2,
    "dismissalFact": 6,
    "sick": 1,
    "vocation": 2,
    "toProject": 9,
    "fromProject": 4
  },
  {
    "id": 27,
    "week": 27,
    "employmentPlan": 4,
    "dismissalPlan": 1,
    "employmentFact": 3,
    "dismissalFact": 1,
    "sick": 2,
    "vocation": 2,
    "toProject": 12,
    "fromProject": 3
  }
]
